# Generated by Django 3.2.9 on 2021-12-02 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'programmingLanguage',
                'verbose_name_plural': 'programmingLanguages',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Personal', verbose_name='Image')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeApp.programminglanguage', verbose_name='Programming Language')),
            ],
            options={
                'verbose_name': 'personal',
                'verbose_name_plural': 'personals',
            },
        ),
    ]
