# Generated by Django 3.2.9 on 2021-12-02 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personal',
            new_name='Users',
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
