# Generated by Django 3.2.9 on 2021-11-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoursesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='price',
            field=models.FloatField(default=10, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
